import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "БСК - Безымянная система кредитования",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{margin: 0, padding: 0, background: 'white', color: 'black'}}
      >
        <div style={{minHeight: 'calc(100vh - 57px)'}}>
          {children}
        </div>

        {/* Подвал */}
        <footer style={{
          padding: 20,
          borderTop: '1px solid #e1e1e1',
          color: '#7f8c8d',
          fontSize: 14,
          textAlign: 'center'
        }}>
          © {new Date().getFullYear()} Все права защищены.
        </footer>
      </body>
    </html>
  );
}
